# using pytest-django - a plugin for pytest that provides
# a set of useful tools for testing Django applications
# and projects. https://pytest-django.readthedocs.io/en/latest/
[pytest]
minversion = 6.0
addopts = -ra -q
DJANGO_SETTINGS_MODULE = config.settings
testpaths =
    site_tests
    integration